name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
        
    - name: Set up sbt launcher
      uses: sbt/setup-sbt@v1

    - name: Run tests
      run: sbt test

  merge:
    name: Merge dependency update
    if: github.actor == 'scala-steward'
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge scala-steward PR
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          ALLOWED_UPDATE: minor
